const PUBLISHERS_LIST_PATH = '/publishers'
const PUBLISHERS_NEW_PATH = `${PUBLISHERS_LIST_PATH}/new`
const PUBLISHERS_EDIT_PATH = `${PUBLISHERS_LIST_PATH}/edit/:id`

const allExport = {
  PUBLISHERS_LIST_PATH,
  PUBLISHERS_NEW_PATH,
  PUBLISHERS_EDIT_PATH,
}

export default allExport
