const CAMPAIGNS_LIST_PATH = '/campaigns'
const CAMPAIGNS_LIST_ALL_CONTACTS_PATH = `${CAMPAIGNS_LIST_PATH}/:id/all`
const CAMPAIGNS_LIST_CHARTS_PATH = `${CAMPAIGNS_LIST_PATH}/:id/charts`

const allExport = {
  CAMPAIGNS_LIST_PATH,
  CAMPAIGNS_LIST_ALL_CONTACTS_PATH,
  CAMPAIGNS_LIST_CHARTS_PATH
}

export default allExport
